# 工作流名称
name: Deploy to Server

# 定义何时触发工作流：这里是在 push 到 main 分支时触发
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 根据你的项目 Node.js 版本设置
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 设置pnpm版本
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      # 安装依赖
      - name: install dependencies
        run: pnpm i

      # 构建
      - name: build
        run: pnpm run -r build

      # 上传服务器
      - name: upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 在 Secrets 中添加你的服务器 IP
          username: ${{ secrets.SERVER_USER }} # 在 Secrets 中添加你的服务器用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }} # GitHub Secrets 中的 SSH 私钥
          port: 22 # SSH 端口，默认为 22
          source: "./apps/live-platform/dist" # 本地文件路径
          target: "/home/www" # 服务器上的目标路径
